name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update
      run: sudo apt update
    - name: cmake
      run: wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz && tar -xvf cmake-3.13.4-Linux-x86_64.tar.gz
    - name: deps
      run: sudo apt install ninja-build cmake bison flex libfl-dev libfreetype6-dev libgif-dev libicns-dev libinput-dev libjpeg-dev libncurses-dev libopenexr-dev libpng-dev libtiff-dev libudev-dev libwebp-dev zlib1g-dev --fix-missing
    - name: mkdir
      run: mkdir generated.x86
    - name: configure
      run: cd generated.x86 && git submodule update --init --recursive ../
    - name: configure
      run: cd generated.x86 && ../cmake-3.13.4-Linux-x86_64/bin/cmake .. -GNinja
    - name: ninja
      run: cd generated.x86 && ninja
    - name: List
      run: find .

